-- Swiggy SQL Case Study
-- Portfolio Analysis | Samarth Pathak

-- =========================================================
-- 1. CUSTOMER & RESTAURANT FUNDAMENTALS
-- =========================================================

-- Q1. Customers living in Delhi
SELECT customer_id, name
FROM customers
WHERE city = 'Delhi';


-- Q2. Average restaurant rating in Mumbai
SELECT city, AVG(rating) AS average_rating
FROM restaurants
GROUP BY city
HAVING city = 'Mumbai';


-- Q3. Customers who have placed at least one order
SELECT DISTINCT
    o.customer_id,
    c.name
FROM orders o
JOIN customers c USING (customer_id);


-- Q4. Total number of orders placed by each customer
SELECT
    c.customer_id,
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o USING (customer_id)
GROUP BY c.customer_id, c.name;


-- =========================================================
-- 2. REVENUE & RESTAURANT ANALYSIS
-- =========================================================

-- Q5. Total revenue generated by each restaurant
SELECT
    r.restaurant_id,
    r.name,
    SUM(p.amount_paid) AS total_revenue
FROM restaurants r
JOIN orders o USING (restaurant_id)
JOIN payment p USING (order_id)
GROUP BY r.restaurant_id, r.name
ORDER BY r.restaurant_id;


-- Q6. Top 5 restaurants by average rating
SELECT
    name,
    rating
FROM restaurants
ORDER BY rating DESC
LIMIT 5;


-- =========================================================
-- 3. CUSTOMER BEHAVIOUR ANALYSIS
-- =========================================================

-- Q7. Customers who have never placed an order
SELECT
    c.customer_id,
    c.name
FROM customers c
LEFT JOIN orders o USING (customer_id)
WHERE o.order_date IS NULL;


-- Q8. Number of orders placed by each customer in Mumbai
SELECT
    c.customer_id,
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o USING (customer_id)
WHERE c.city = 'Mumbai'
GROUP BY c.customer_id, c.name;


-- Q9. Orders placed in the last 30 days of the dataset
-- Uses the latest order date in the dataset as the reference point.
SELECT
    order_id,
    order_date
FROM orders
WHERE order_date >= DATE_ADD(
    (SELECT MAX(order_date) FROM orders),
    INTERVAL -30 DAY
);


-- Q11. Customers who placed orders on exactly three different days
SELECT
    c.customer_id,
    c.name,
    COUNT(DISTINCT o.order_date) AS distinct_order_days
FROM customers c
JOIN orders o USING (customer_id)
GROUP BY c.customer_id, c.name
HAVING COUNT(DISTINCT o.order_date) = 3;


-- =========================================================
-- 4. DELIVERY PARTNER ANALYSIS
-- =========================================================

-- Q10. Delivery partners who completed more than one delivery
SELECT
    dp.partner_id,
    dp.name,
    COUNT(od.order_id) AS total_deliveries
FROM deliverypartners dp
JOIN orderdelivery od USING (partner_id)
GROUP BY dp.partner_id, dp.name
HAVING COUNT(od.order_id) > 1;


-- Q12. Delivery partner who worked with the most different customers
SELECT
    dp.partner_id,
    dp.name,
    COUNT(DISTINCT o.customer_id) AS total_customers
FROM deliverypartners dp
JOIN orderdelivery od USING (partner_id)
JOIN orders o USING (order_id)
GROUP BY dp.partner_id, dp.name
ORDER BY total_customers DESC
LIMIT 1;


-- =========================================================
-- 5. ADVANCED RELATIONAL ANALYSIS
-- =========================================================

-- Q13. Customers in the same city who ordered from the same
-- restaurant on different dates
SELECT
    c1.name AS customer1,
    c2.name AS customer2,
    c1.city AS city1,
    c2.city AS city2,
    r.name AS restaurant
FROM customers c1
JOIN orders o1
    ON c1.customer_id = o1.customer_id
JOIN orders o2
    ON o2.restaurant_id = o1.restaurant_id
JOIN customers c2
    ON c1.city = c2.city
    AND c1.name <> c2.name
    AND o2.customer_id = c2.customer_id
JOIN restaurants r
    ON o1.restaurant_id = r.restaurant_id
WHERE o1.order_date <> o2.order_date;
